### PR TITLE
Update fabric.mod.json to include CC dependency

### PR DESCRIPTION
**Pull request by EliSauder**
Added dependency on cooldown-coordinator

### CODE REVIEW

**Comment by enjarai** [comment]
Is there a point to doing this? Cooldown Coordinator is JiJ'ed, so will be available any time the mod is loaded.

**Comment by gniftygnome** [comment]
Generally I'd say not, but it's worth pointing out Fabric and Quilt will both silently discard JiJ'd mods from the load list if they conflict with anything ... unless they're listed as a dep in the json.

**Comment by enjarai** [comment]
I wasn't aware of that behaviour, I suppose it definitely can't hurt to add it either way.

The dep on a specific version might not be ideal though. I assume the API wont break on non-major updates at least, so it should be safe to be a little more generous with that, in case some other mod includes a newer version.

**Comment by gniftygnome** [comment]
Yeah, I haven't broken the API yet and I don't foresee a need so it should be a while at least.  The versions have more to do with what versions of Minecraft they work with than anything else.  Ductwork specifies a dep of `*` because if it's a version of CC that'll load it should be good.

**Comment by EliSauder** [comment]
I just updated it to be any future minor version of CC

**Comment by enjarai** [comment]
That works. 👍

**Pull request merged**
